ALTER TABLE tasks DROP CONSTRAINT IF EXISTS fk_task_module;
ALTER TABLE tasks ALTER COLUMN module_id DROP NOT NULL;
ALTER TABLE tasks ADD CONSTRAINT fk_task_module FOREIGN KEY (module_id) REFERENCES modules(id) ON DELETE SET NULL;
